# site settings
title: Pest Control Company
email: bbodine1@gmail.com
description: >-
  Pest Control Services for your area. We have the best
  pest solutions and the best prices to protect the things
  you love from pests.
reviewlimit: 5
gtm-id:    # XXXXXXX this is the 7 digit google tag manager id number after the GTM-
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# General data
logo-dark: /img/logo-dark.svg
logo-light: /img/logo-light.svg
street: 123 Main St.
city: YourTown
state: AL
zipcode: 55555
phone: '(256) 555-5011'
service-area: 'North Alabama including Hartselle, Decatur, Madison, Athens, Moulton, and Cullman'

# Social links
facebook: https://www.facebook.com/BetterWayPestControl/
google: https://goo.gl/maps/c3yoeyEDwTn

# Work Hours
work-hours:
  - day: Sunday
    hours: Closed
  - day: Monday
    hours: 7am - 6pm
  - day: Tuesday
    hours: 7am - 6pm
  - day: Wednesday
    hours: 7am - 6pm
  - day: Thursday
    hours: 7am - 6pm
  - day: Friday
    hours: 7am - 6pm
  - day: Saturday
    hours: 7am - 6pm


# Facebook Share Meta
share-website: https://mywebsite.com
share-title: This is the title of the share
share-description: >-
  This is the description of the share. It should be a bit
  longer. It can be several sentences.
share-image: share.jpg

# Navigation
nav:
  - title: Home
    url: /
    subpages:

  - title: About
    url: /about
    subpages:

  - title: Services
    url: /services
    subpages:
      - title: Residential Pest Control
        url: /services/residential
      - title: Mosquito Control
        url: /services/mosquito
      - title: Rodent Control
        url: /services/rodents

  - title: Payments
    url: /payments
    subpages:


# build settings
source: src
destination: dist
markdown: kramdown

plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions
sass:
  style: compressed
  load_paths:
    - _sass
    - ../node_modules

collections:
  pages:
    output: true
    permalink: /:path
  reviews:
    output: false
    
# Include
# include:
#   - _pages
#   - _reviews

# Exclude
# exclude:
#   - 'package.json'
#   - 'Gemfile'
#   - '*.gemspec'
#   - '*.lock'
